apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubuntu-netboot.fullname" . }}
  labels:
    {{- include "ubuntu-netboot.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ubuntu-netboot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "ubuntu-netboot.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      containers:
        - name: ubuntu-netboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/config/entrypoint.sh"]
          ports:
            - name: tftp
              containerPort: 69
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tftp-data
              mountPath: /srv/tftp
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ubuntu-netboot.fullname" . }}-config
            defaultMode: 0755
        - name: tftp-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "ubuntu-netboot.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
