{{- if .Values.notifications.sms.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website-monitor.fullname" . }}-smtp
  labels:
    {{- include "website-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-host: {{ .Values.notifications.sms.smtp.host | quote }}
  smtp-username: {{ .Values.notifications.sms.smtp.username | quote }}
  smtp-password: {{ .Values.notifications.sms.smtp.password | quote }}
{{- end }}
