{{- if .Values.mjpgStreamer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "octoprint.fullname" . }}-mjpg-streamer
  labels:
    {{- include "octoprint.mjpgStreamer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mjpgStreamer.service.type }}
  ports:
    - port: {{ .Values.mjpgStreamer.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "octoprint.mjpgStreamer.selectorLabels" . | nindent 4 }}
{{- end }}
