apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "avahi-daemon.fullname" . }}
  labels:
    {{- include "avahi-daemon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "avahi-daemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "avahi-daemon.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: avahi-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/config/setup.sh"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: host-root
              mountPath: /host
            - name: host-run
              mountPath: /run
            - name: host-var-run
              mountPath: /var/run
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "avahi-daemon.fullname" . }}-config
            defaultMode: 0755
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: host-run
          hostPath:
            path: /run
            type: Directory
        - name: host-var-run
          hostPath:
            path: /var/run
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
