{{- if and .Values.ingress.enabled .Values.ingress.tls -}}
{{- $cert := genSelfSignedCert (index .Values.ingress.hosts 0).host nil (list (index .Values.ingress.hosts 0).host) 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.ingress.tls 0).secretName }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
